// <auto-generated />
namespace SistemaDeVendas.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class cricaodeentidadeseconeccaocomobanco : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(cricaodeentidadeseconeccaocomobanco));
        
        string IMigrationMetadata.Id
        {
            get { return "201909191904059_cricao de entidades e coneccao com o banco"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
