// <auto-generated />
namespace SistemaDeVendas.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class Casa02102019 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Casa02102019));
        
        string IMigrationMetadata.Id
        {
            get { return "201910021744566_Casa02102019"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
